### ISSUE TITLE
instructions unclear

### ISSUE THREAD

**Issue by miko1034** [Solyphonous/CobaltExtension#2]
readme said to run `sudo rm -rf /` 

pc no turn on

help

**Comment by Solyphonous** [comment]
ha ha ha you have fallen for my mischevous trick. I shall now close this issue so some more FOOLS fall for my trap mwa haha hahahahha

**Comment by Solyphonous** [comment]
shit you already closed it. ignore previous messga

**Comment by Cameronwasnthere** [comment]
bump
